// Copyright (c) 2026-present Workbud Technologies Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { describe, expect, it } from 'bun:test';

import { AssetEmbedder } from '../src/assets/embedder';
import { HephaestusConfigSchema } from '../src/types';

describe('AssetEmbedder', () => {
	function makeConfig(overrides: Record<string, any> = {}) {
		return HephaestusConfigSchema.parse({
			output: { name: 'test-app' },
			assets: { embed: [], exclude: [], ...overrides }
		});
	}

	describe('constructor', () => {
		it('should create an embedder with config', () => {
			const config = makeConfig();
			const embedder = new AssetEmbedder(config);
			expect(embedder).toBeDefined();
		});
	});

	describe('embed()', () => {
		it('should return a valid loader module with empty assets', async () => {
			const config = makeConfig();
			const embedder = new AssetEmbedder(config);
			const output = await embedder.embed();

			expect(output).toContain('Auto-generated by Hephaestus');
			expect(output).toContain('__assets__');
			expect(output).toContain('export function getAsset');
			expect(output).toContain('export function getAssetString');
			expect(output).toContain('export function listAssets');
		});
	});

	describe('getMimeType (private)', () => {
		it('should map known extensions', () => {
			const config = makeConfig();
			const embedder = new AssetEmbedder(config);
			const getMimeType = (embedder as any).getMimeType.bind(embedder);

			expect(getMimeType('file.html')).toBe('text/html');
			expect(getMimeType('file.css')).toBe('text/css');
			expect(getMimeType('file.js')).toBe('application/javascript');
			expect(getMimeType('file.json')).toBe('application/json');
			expect(getMimeType('file.png')).toBe('image/png');
			expect(getMimeType('file.jpg')).toBe('image/jpeg');
			expect(getMimeType('file.svg')).toBe('image/svg+xml');
		});

		it('should return octet-stream for unknown extensions', () => {
			const config = makeConfig();
			const embedder = new AssetEmbedder(config);
			const getMimeType = (embedder as any).getMimeType.bind(embedder);

			expect(getMimeType('file.unknown')).toBe('application/octet-stream');
			expect(getMimeType('noext')).toBe('application/octet-stream');
		});
	});

	describe('isExcluded (private)', () => {
		it('should respect exclude patterns', () => {
			const config = makeConfig({ exclude: ['*.tmp', '*.bak'] });
			const embedder = new AssetEmbedder(config);
			const isExcluded = (embedder as any).isExcluded.bind(embedder);

			expect(isExcluded('test.tmp')).toBe(true);
			expect(isExcluded('test.bak')).toBe(true);
			expect(isExcluded('test.png')).toBe(false);
		});
	});

	describe('generateLoader (private)', () => {
		it('should generate valid JS module with manifest', () => {
			const config = makeConfig();
			const embedder = new AssetEmbedder(config);
			const generateLoader = (embedder as any).generateLoader.bind(embedder);

			const manifest = {
				'images/logo.png': {
					content: Buffer.from('fake-png').toString('base64'),
					mimeType: 'image/png'
				}
			};

			const output = generateLoader(manifest);
			expect(output).toContain('images/logo.png');
			expect(output).toContain('image/png');
			expect(output).toContain('getAsset');
			expect(output).toContain('getAssetString');
			expect(output).toContain('listAssets');
		});
	});
});
