// Copyright (c) 2026-present Workbud Technologies Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type { HephaestusConfig } from '../types';

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Generates a multi-stage Dockerfile for compiled Elysium binaries.
 *
 * The runtime stage uses Alpine (not Bun) because the compiled binary
 * is self-contained. Healthcheck uses `wget` (available in Alpine base).
 *
 * @author Axel Nana <axel.nana@workbud.com>
 */
export class DockerGenerator {
	constructor(private config: HephaestusConfig) {}

	/**
	 * Generates the Dockerfile and writes it to the output directory.
	 * @author Axel Nana <axel.nana@workbud.com>
	 * @param outputDir The directory to write the Dockerfile to.
	 */
	public generate(outputDir: string): void {
		mkdirSync(outputDir, { recursive: true });

		const dockerfile = this.renderDockerfile();
		writeFileSync(join(outputDir, 'Dockerfile'), dockerfile);
	}

	private renderDockerfile(): string {
		const buildImage = this.config.docker?.buildImage ?? 'oven/bun:1-alpine';
		const runtimeImage = this.config.docker?.runtimeImage ?? 'alpine:3.19';
		const binaryName = this.config.output.name;
		const expose = this.config.docker?.expose ?? [];
		const healthcheck = this.config.docker?.healthcheck;

		// Template literals — no Handlebars needed
		return `# Generated by Hephaestus
FROM ${buildImage} AS builder
WORKDIR /app
COPY . .
RUN bun install --frozen-lockfile --production
RUN bun run build

FROM ${runtimeImage}
WORKDIR /app
COPY --from=builder /app/dist/${binaryName} /app/${binaryName}
${expose.map((p: number) => `EXPOSE ${p}`).join('\n')}
${healthcheck ? `HEALTHCHECK --interval=${healthcheck.interval} CMD wget -qO- http://localhost:${expose[0] ?? 3000}${healthcheck.path} || exit 1` : ''}
ENTRYPOINT ["./${binaryName}"]
`;
	}
}
